version: 2.0
jobs:
  build:
    docker:
      - image: circleci/elixir:1.7
    working_directory: ~/zmq_ex
    steps:
      - checkout
      - run: mkdir -p ~/junit
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: JUNIT_DIR=~/junit mix test
      - run:
          name: Send coveralls data
          command: MIX_ENV=test mix coveralls.circle
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
